// Deterministic file builders for the Level-1 technical fixes. The MCP returns
// these as ready-to-commit files so an agent can drop them straight into the
// user's repo — no LLM call needed (and no hallucinated paths).

import { evidenceForCheck, type SiteAudit, type SiteCrawl } from "../audit/site";
import type { Database } from "../supabase/database.types";

type BrandRow = Database["public"]["Tables"]["brands"]["Row"];
type BrandFile = Pick<BrandRow, "company" | "url" | "description" | "industry">;

// The AI answer-engine crawlers robots.txt should welcome (mirrors lib/audit/site.ts).
// Exported so our own app/robots.ts welcomes the exact same set — single source of truth.
export const AI_CRAWLERS = ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "PerplexityBot", "Google-Extended"];

function origin(url: string): string | null {
  try {
    return new URL(/^https?:\/\//i.test(url) ? url : `https://${url}`).origin;
  } catch {
    return null;
  }
}

function oneLine(s: string, max = 160): string {
  const t = s.replace(/\s+/g, " ").trim();
  return t.length > max ? `${t.slice(0, max - 1)}…` : t;
}

// --- robots.txt -------------------------------------------------------------

// User-agents that already have an explicit group in the existing file.
function existingAgents(txt: string): Set<string> {
  const set = new Set<string>();
  for (const m of txt.matchAll(/^\s*user-agent:\s*(.+?)\s*$/gim)) set.add(m[1].toLowerCase());
  return set;
}

// Specific Disallow paths under `User-agent: *` — the real protections we carry
// onto the AI-bot groups (dropping a bare `Disallow: /`, which is the very block
// we want to lift, not preserve).
function globalDisallows(txt: string): string[] {
  const out: string[] = [];
  let inStar = false;
  for (const raw of txt.split(/\r?\n/)) {
    const line = raw.trim();
    const ua = line.match(/^user-agent:\s*(.+)$/i);
    if (ua) {
      inStar = ua[1].trim() === "*";
      continue;
    }
    if (!line) {
      inStar = false; // a blank line ends the group
      continue;
    }
    if (inStar) {
      const d = line.match(/^disallow:\s*(.*)$/i);
      if (d && d[1].trim()) out.push(d[1].trim());
    }
  }
  return [...new Set(out)].filter((p) => p !== "/");
}

// Non-destructively fold AI-crawler allow rules into the user's EXISTING
// robots.txt: keep every line they already have (so /admin, /api Disallows
// survive), add a group for each AI bot that lacks one — carrying the site's
// real Disallow paths so those bots still respect protected areas — and add a
// Sitemap line if missing.
function mergeRobots(existing: string, o: string | null): string {
  const have = existingAgents(existing);
  const protect = globalDisallows(existing);
  const additions = AI_CRAWLERS.filter((b) => !have.has(b.toLowerCase())).map((bot) =>
    [`User-agent: ${bot}`, "Allow: /", ...protect.map((p) => `Disallow: ${p}`)].join("\n"),
  );

  let out = existing.replace(/\s+$/, "");
  if (additions.length) {
    out += `\n\n# AI answer-engine crawlers (added by Clerow — your existing rules above are preserved)\n${additions.join("\n\n")}`;
  }
  if (o && !/^\s*sitemap:\s*http/im.test(existing)) out += `\n\nSitemap: ${o}/sitemap.xml`;
  return `${out}\n`;
}

export function buildRobotsTxt(brand: Pick<BrandRow, "url">, crawl?: SiteCrawl | null): string {
  const o = origin(brand.url);
  const existing = crawl?.robotsTxt?.trim();
  // Merge with the real file when we have one — never hand back a destructive
  // standalone that would strip their existing protections.
  if (existing) return mergeRobots(existing, o);

  const lines: string[] = ["# Allow AI answer-engine crawlers (generated by Clerow)"];
  for (const bot of AI_CRAWLERS) lines.push(`User-agent: ${bot}`, "Allow: /", "");
  lines.push("User-agent: *", "Allow: /");
  if (o) lines.push("", `Sitemap: ${o}/sitemap.xml`);
  return lines.join("\n") + "\n";
}

// --- llms.txt ---------------------------------------------------------------

export function buildLlmsTxt(brand: BrandFile, crawl?: SiteCrawl | null): string {
  const o = origin(brand.url) ?? brand.url;
  const name = brand.company || o;
  const summary =
    brand.description ||
    crawl?.home?.description ||
    crawl?.home?.title ||
    `${name}${brand.industry ? ` — ${brand.industry}` : ""}.`;

  // Key pages from the REAL crawl — so we never link a /pricing or /faq that
  // doesn't exist. With no crawl data we list only the homepage (safe) rather
  // than guess a generic SaaS page set.
  const pageLines = [`- ${o}/ : ${oneLine(crawl?.home?.title || `Overview of what ${name} does and who it's for`)}`];
  for (const p of crawl?.pages ?? []) {
    const desc = p.description || p.title;
    pageLines.push(desc ? `- ${p.url} : ${oneLine(desc)}` : `- ${p.url}`);
  }

  return [
    `# ${name}`,
    "",
    `> ${oneLine(summary)}`,
    "",
    `Website: ${o}`,
    brand.industry ? `Category: ${brand.industry}` : "",
    "",
    "## Key pages",
    ...pageLines,
    "",
    "## About",
    `${oneLine(summary)} Keep this file updated as the canonical, plain-language summary you want AI assistants to repeat about ${name}.`,
    "",
  ]
    .filter((l) => l !== "")
    .join("\n") + "\n";
}

// The deterministic, no-LLM content for a task, keyed by its ladder_key. This is
// the single source of truth shared by the MCP (get_task_content) and the
// dashboard "Make content" route, so the two can't drift apart. Routes by the
// audit check's `fix.artifact`:
//  • fix.artifact "robots"/"llms" -> the generated file (grounded in the crawl)
//  • any other audit-* fix        -> the audit's fix detail + diagnostic steps
//    (CODE/INFRA fixes — server errors, missing tags, no SSR — never prose). A
//    robots.txt that returns a 500 has no artifact, so it correctly lands here.
//  • everything else (real content tasks) -> null, so the caller falls back to
//    a content brief / LLM draft.
// The crawler's raw observation for a failing check — the status code and (on
// error) what the server actually sent. Shipping this with the diagnostic steps
// saves the agent the root-cause hunt the crawler already did. "" when the audit
// predates evidence retention.
function observedSection(checkId: string, audit: SiteAudit): string {
  const e = evidenceForCheck(audit, checkId);
  if (!e) return "";
  const status = e.httpStatus == null ? "no response (timeout or blocked)" : `HTTP ${e.httpStatus}`;
  const lines = [`## Observed (by Clerow's crawler, ${audit.fetchedAt})`, "", `- GET ${e.url} → ${status}`];
  if (e.bodySnippet) lines.push(`- Response body began: "${e.bodySnippet}"`);
  return lines.join("\n") + "\n\n";
}

export function deterministicTaskContent(
  key: string,
  brand: BrandFile,
  audit: SiteAudit | null,
): string | null {
  const crawl = audit?.crawl ?? null;
  if (audit && key.startsWith("audit-")) {
    const check = audit.checks.find((c) => `audit-${c.id}` === key);
    if (check?.fix?.artifact === "robots") return buildRobotsTxt(brand, crawl);
    if (check?.fix?.artifact === "llms") return buildLlmsTxt(brand, crawl);
    if (check?.fix) {
      const steps = check.fix.steps.length
        ? "\n\n## Steps\n" + check.fix.steps.map((s) => `- ${s}`).join("\n")
        : "";
      return `${observedSection(check.id, audit)}## ${check.fix.title}\n\n${check.fix.detail}${steps}`;
    }
  }
  // Fallback when the audit/check isn't in hand (e.g. the non-ladder task path):
  // route by key so robots/llms still return a best-effort file.
  if (key.includes("robots")) return buildRobotsTxt(brand, crawl);
  if (key.includes("llms")) return buildLlmsTxt(brand, crawl);
  return null;
}
