// Deterministic file builders for the Level-1 technical fixes. The MCP returns
// these as ready-to-commit files so an agent can drop them straight into the
// user's repo — no LLM call needed (and no hallucinated paths).

import type { SiteAudit } from "../audit/site";
import type { Database } from "../supabase/database.types";

type BrandRow = Database["public"]["Tables"]["brands"]["Row"];

// The AI answer-engine crawlers robots.txt should welcome (mirrors lib/audit/site.ts).
const AI_CRAWLERS = ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "PerplexityBot", "Google-Extended"];

function origin(url: string): string | null {
  try {
    return new URL(/^https?:\/\//i.test(url) ? url : `https://${url}`).origin;
  } catch {
    return null;
  }
}

export function buildRobotsTxt(brand: Pick<BrandRow, "url">): string {
  const lines: string[] = ["# Allow AI answer-engine crawlers (generated by Clerow)"];
  for (const bot of AI_CRAWLERS) {
    lines.push(`User-agent: ${bot}`, "Allow: /", "");
  }
  lines.push("User-agent: *", "Allow: /");
  const o = origin(brand.url);
  if (o) lines.push("", `Sitemap: ${o}/sitemap.xml`);
  return lines.join("\n") + "\n";
}

export function buildLlmsTxt(brand: Pick<BrandRow, "company" | "url" | "description" | "industry">): string {
  const o = origin(brand.url) ?? brand.url;
  const name = brand.company || o;
  const summary = brand.description || `${name}${brand.industry ? ` — ${brand.industry}` : ""}.`;
  return [
    `# ${name}`,
    "",
    `> ${summary}`,
    "",
    `Website: ${o}`,
    brand.industry ? `Category: ${brand.industry}` : "",
    "",
    "## Key pages",
    `- ${o}/ : Overview of what ${name} does and who it's for`,
    `- ${o}/pricing : Plans and pricing`,
    `- ${o}/faq : Frequently asked questions`,
    `- ${o}/blog : Guides, comparisons, and updates`,
    "",
    "## About",
    `${summary} Keep this file updated as the canonical, plain-language summary you want AI assistants to repeat about ${name}.`,
    "",
  ]
    .filter((l) => l !== "")
    .join("\n") + "\n";
}

// The deterministic, no-LLM content for a task, keyed by its ladder_key. This is
// the single source of truth shared by the MCP (get_task_content) and the
// dashboard "Make content" route, so the two can't drift apart:
//  • robots.txt / llms.txt  -> the generated file
//  • any other audit-* fix  -> the audit's own fix detail + diagnostic steps.
//    These are CODE/INFRA fixes (server errors, missing tags, no SSR) — NOT
//    prose — so they must never get the AEO content-writing brief.
//  • everything else (real content tasks) -> null, so the caller falls back to
//    a content brief / LLM draft.
export function deterministicTaskContent(
  key: string,
  brand: Pick<BrandRow, "company" | "url" | "description" | "industry">,
  audit: SiteAudit | null,
): string | null {
  // Checked before the generic audit- branch: their keys start with "audit-" too.
  if (key.includes("robots")) return buildRobotsTxt(brand);
  if (key.includes("llms")) return buildLlmsTxt(brand);
  if (key.startsWith("audit-")) {
    const check = audit?.checks.find((c) => `audit-${c.id}` === key);
    if (check?.fix) {
      const steps = check.fix.steps.length
        ? "\n\n## Steps\n" + check.fix.steps.map((s) => `- ${s}`).join("\n")
        : "";
      return `## ${check.fix.title}\n\n${check.fix.detail}${steps}`;
    }
  }
  return null;
}
